env:
    browser: true
    es2021: true
extends:
    - plugin:react/recommended
    - standard
    - prettier
plugins:
    - react
    - prettier
rules:
    "prettier/prettier": "error"
parserOptions:
    ecmaVersion: latest
    sourceType: module
